name: deepscribe2
channels:
 - pytorch
 - nvidia
 - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda=11.6
  - torchaudio
  - black
  - pytorch-lightning
  - torchmetrics
  - nb_conda
  - numpy
  - matplotlib
  - Pillow
  - tqdm
  - opencv
  - ipykernel
  - ipywidgets